vich_uploader:
    db_driver: orm

    mappings:
        pub_image:
            uri_prefix: /uploads/pubs
            upload_destination: '%kernel.project_dir%/public//uploads/pubs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
